// Generates db/seed.sql from content/portfolio.json. Re-running the seed replaces all content
// tables (messages are left alone), so edit the JSON and re-seed, or edit D1 directly — not both.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const data = JSON.parse(await readFile(path.join(root, "content/portfolio.json"), "utf8"));

const sql = (value) => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return `'${text.replaceAll("'", "''")}'`;
};

const insert = (table, row) =>
  `INSERT INTO ${table} (${Object.keys(row).join(", ")}) VALUES (${Object.values(row).map(sql).join(", ")});`;

const { profile: p } = data;
const statements = [
  "-- Generated by scripts/build-seed.mjs from content/portfolio.json. Do not edit by hand.",
  ...["profile", "socials", "stats", "skill_groups", "projects", "experience", "education", "organizations", "certifications", "moments", "translations"].map(
    (table) => `DELETE FROM ${table};`,
  ),
  insert("profile", {
    id: 1,
    first_name: p.firstName,
    last_name: p.lastName,
    full_name: p.fullName,
    role: p.role,
    tagline: p.tagline,
    intro: p.intro,
    summary: p.summary,
    location: p.location,
    email: p.email,
    availability: p.availability,
    current_company: p.currentCompany,
    portrait_key: p.portrait,
    portrait_cutout_key: p.portraitCutout,
    about_image_key: p.aboutImage,
    about_image_caption: p.aboutImageCaption,
    og_image_key: p.ogImage,
    resume_key: p.resume,
  }),
  ...data.socials.map((s, i) => insert("socials", { label: s.label, handle: s.handle, url: s.url, sort: i })),
  ...data.stats.map((s, i) => insert("stats", { value: s.value, label: s.label, detail: s.detail, sort: i })),
  ...data.skills.map((g, i) => insert("skill_groups", { title: g.title, kind: g.kind, items: g.items, sort: i })),
  ...data.projects.map((pr, i) =>
    insert("projects", {
      slug: pr.slug,
      name: pr.name,
      category: pr.category,
      tagline: pr.tagline,
      summary: pr.summary,
      description: pr.description,
      role: pr.role,
      role_detail: pr.roleDetail,
      company: pr.company,
      year: pr.year,
      url: pr.url,
      cover_key: pr.cover,
      cover_alt: pr.coverAlt,
      cover_focus: pr.coverFocus ?? "start",
      theme: pr.theme,
      metrics: pr.metrics,
      modules: pr.modules,
      flows: pr.flows,
      stories: pr.stories,
      gallery: pr.gallery,
      sort: i,
    }),
  ),
  ...data.experience.map((e, i) =>
    insert("experience", {
      company: e.company,
      company_note: e.companyNote,
      role: e.role,
      location: e.location,
      start_date: e.start,
      end_date: e.end,
      summary: e.summary,
      points: e.points,
      sort: i,
    }),
  ),
  ...data.education.map((e, i) =>
    insert("education", {
      school: e.school,
      degree: e.degree,
      location: e.location,
      period: e.period,
      gpa: e.gpa,
      honor: e.honor,
      image_key: e.image,
      image_alt: e.imageAlt,
      points: e.points,
      sort: i,
    }),
  ),
  ...data.organizations.map((o, i) =>
    insert("organizations", {
      name: o.name,
      role: o.role,
      location: o.location,
      period: o.period,
      summary: o.summary,
      points: o.points,
      sort: i,
    }),
  ),
  ...data.certifications.map((c, i) => insert("certifications", { title: c.title, issuer: c.issuer, year: c.year, sort: i })),
  ...(data.moments ?? []).map((m, i) => insert("moments", { image_key: m.src, alt: m.alt, caption: m.caption, sort: i })),
  ...Object.entries(data.translations ?? {}).map(([locale, t]) => insert("translations", { locale, data: t })),
];

await mkdir(path.join(root, "db"), { recursive: true });
await writeFile(path.join(root, "db/seed.sql"), statements.join("\n") + "\n");
console.log(`db/seed.sql: ${statements.length - 1} statements`);
